FROM python:3.10-bullseye
ENV TZ=Europe/Paris
WORKDIR /streamlit_app2_dashboard

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# EXPOSE 80
EXPOSE 8502

COPY OracDashboard_BE.py OracDashboard_BE.py
COPY . /streamlit_app2_dashboard/

RUN mkdir ~/.streamlit

RUN cp .streamlit/config.toml ~/.streamlit/config.toml
RUN cp .streamlit/credentials.toml ~/.streamlit/credentials.toml

ENTRYPOINT ["streamlit", "run"]
CMD ["OracDashboard_BE.py"]
