FROM postgres:latest
ENV TZ=Europe/Paris


EXPOSE 5432

ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=postgres

# COPY create_fixtures.sql /docker-entrypoint-initdb.d/create_fixtures.sql