version: '3'
services:
  python:
    container_name: python_dashboard_
    build: ./streamlit_app
    depends_on:
        - db
    ports:
      - 80:80
      - 8501:8501
    networks:
      - docker_network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_
    environment:
      - TZ=Europe/Paris
    ports:
      - 1883:1883
      - 8883:8883
    networks:
      - docker_network
    volumes:
      - C:/docker/orac/mosquitto/mosquitto-data:/mosquitto/data
      - C:/docker/orac/mosquitto/mosquitto-logs:/mosquitto/logs
      - C:/docker/orac/mosquitto/mosquitto-conf:/mosquitto/config
    restart: unless-stopped

  db:
    container_name: postgres_db_
    build: ./database
    ports:
      - 5432:5432
    networks:
      - docker_network
    # volumes: # do keep for persistent database data
    #   - ./data:/var/lib/postgresql/data


networks:
  docker_network:
    driver: bridge

    